package com.glodon.linglong.engine.core.tx;

import com.glodon.linglong.engine.core.TreeCursor;

/**
 * _TreeCursor which uses an explicit transaction when none is specified, excluding loads.
 *
 * @author Generated by PageAccessTransformer from TxnTreeCursor.java
 */
final class TxnTreeCursor extends TreeCursor {
    TxnTreeCursor(TxnTree tree, Transaction txn) {
        super(tree, txn);
    }

    TxnTreeCursor(_TxnTree tree) {
        super(tree);
    }

    // Note: Replicated transactions (via redo logging) require undo logging for all
    // operations, because rollback is required when commits are rejected.

    @Override
    protected int storeMode() {
        // Always undo.
        return 1;
    }
}
