spring:
  main:
    web-environment: true
  application:
    name: LingLongDB

server:
  port: 8080

logging:
  level:
    root: info

endpoints:
  shutdown:
    enabled: true
    sensitive: false

management:
  address: 127.0.0.1
  context-path: /management

##Linglongdb config
linglongdb:
  baseDir: /root/test/data
  pageSize: 4096
  minCacheSize: 100000000
  maxCacheSize: 100000000
  lockTimeout: 1000
  checkpointRate: 1000
  durabilityMode: SYNC
  checkpointSizeThreshold: 1048576
  checkpointDelayThreshold: 60000
  maxCheckpointThreads: 8
  replicaEnabled: true
  replicaPort: 7070
  replicaRole: NORMAL
  replicaGroupToken: 1
#  replicaSeedAddresses:
#    - 10.2.76.44:7070
  http:
    serverHost: 0.0.0.0
    serverPort: 7001
    maxThreads: 200
    minSpareThreads: 200
    maxConnections: -1
    handlerVersion: v1
  rpc:
    serverHost: 0.0.0.0
    serverPort: 7002
    useEpoll: false
    payload: 16777216
    sendTimeout: 5000
    readTimeout: 15000
    connectTimeout: 5000
    threadConcurrency: 200
    sendBufferSize: 65535
    receiveBufferSize: 65535
    heartBeatExpireInterval: 60000








